version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/ruby:latest-node
    working_directory: ~/repo

jobs:
    build:
        executor: my-executor
        steps:
            - checkout
            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v3-cache-{{ checksum "package-lock.json" }}-{{ checksum "Gemfile.lock"}}
                      - v3-cache-
            - run:
                  name: Install Dependencies
                  command: |
                    bundle install
                    npm install
                    sudo npm install -g pug
            - save_cache:
                  key: v3-cache-{{ checksum "package-lock.json" }}-{{ checksum "Gemfile.lock"}}
                  paths:
                      - ./node_modules
                      - ./vendor/bundle
            - run:
                  name: Build
                  command: |
                    bundle exec jekyll build --verbose
            - persist_to_workspace:
                root: ~/repo
                # Must be relative path from root
                paths:
                    - ./
    deploy:
        executor: my-executor
        steps:
            - attach_workspace:
                at: ~/repo
            - run: cd /tmp/repo
            - run:
                  name: Firebase Deploy
                  command:
                    ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --non-interactive
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: circleci
