version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10.16.0
        working_directory: ~/repo
        steps:
            - checkout
            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      - v1-dependencies-
            - run:
                  name: Install Dependencies
                  command: |
                    npm install
                    gem install bundler jekyll
            - save_cache:
                  key: v1-npm-deps-{{ checksum "package-lock.json" }}
                  paths:
                      - ./node_modules
            - run:
                  name: Build
                  command: |
                    cd ~/repo/website
                    bundle exec jekyll build --verbose
            - run:
                  name: Firebase Deploy
                  command: |
                    cd ~/repo
                    ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --non-interactive
