version: 2
jobs:
    build:
        filters:
            branches:
                ignore: master
        docker:
            - image: circleci/ruby:latest-node
        working_directory: ~/repo
        steps:
            - checkout
            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v2-cache-{{ checksum "package-lock.json" }}-{{ checksum "Gemfile.lock"}}
                      - v3-cache-{{ checksum "package-lock.json" }}-{{ checksum "Gemfile.lock"}}
                      - v3-cache-
            - run:
                  name: Install Dependencies
                  command: |
                    ls -a ./
                    bundle install
                    ls -a ./
                    ls $BUNDLE_PATH
                    npm install
                    sudo npm install -g pug
            - save_cache:
                  key: v3-cache-{{ checksum "package-lock.json" }}-{{ checksum "Gemfile.lock"}}
                  paths:
                      - ./node_modules
                      - ./vendor/bundle
            - run:
                  name: Build
                  command: |
                    bundle exec jekyll build --verbose
    deploy:
        filters:
            branches:
                only: master
        docker:
            - image: circleci/ruby:latest-node
        working_directory: ~/repo
        steps:
            - checkout
            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v2-cache-{{ checksum "package-lock.json" }}-{{ checksum "Gemfile.lock"}}
                      - v2-cache-{{ checksum "package-lock.json" }}
                      - v2-cache-
            - run:
                  name: Install Dependencies
                  command: |
                    ls $BUNDLE_PATH
                    bundle install
                    npm install
                    sudo npm install -g pug
            - save_cache:
                  key: v2-cache-{{ checksum "package-lock.json" }}-{{ checksum "Gemfile.lock"}}
                  paths:
                      - ./node_modules
                      - $BUNDLE_PATH
            - run:
                  name: Build
                  command: |
                    bundle exec jekyll build --verbose
            - run:
                  name: Firebase Deploy
                  command:
                    ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --non-interactive
