version: 2
jobs:
    build:
        docker:
            - image: circleci/ruby:latest-node
        working_directory: ~/repo
        steps:
            - checkout
            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package-lock.json" }}
                      - v1-dependencies-
            - run:
                  name: Install Dependencies
                  command: |
                    bundle install --path vendor/bundle
                    npm install
                    sudo npm install -g pug
            - save_cache:
                  key: v1-dependencies-{{ checksum "package-lock.json" }}
                  paths:
                      - ./node_modules
                      - vendor/bundle
            - run:
                  name: Build
                  command: |
                    bundle exec jekyll build --verbose
    deploy:
        machine:
            enabled: true
        requires:
            - build
        branches:
            only:
                - master
        working_directory: ~/repo
        steps:
            - run:
                  name: Firebase Deploy
                  command:
                    ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --non-interactive
